DATALEN_MAIN        = 2048;
DATALEN_ALL         = 4096;
TIME_INCR_PER_DAY   = 1440;

VERSION_COL         = 1;
ANTENNA_COL         = 2;
CENTER_FREQ_HZ_COL  = 4;
BINSIZE_KHZ_COL     = 5;
AVG_PERIOD_COL      = 6;
DATA_DB_MAIN_COLS   = 7:(DATALEN_MAIN-1+7);
DATA_DB_ALL_COLS    = 7:(DATALEN_ALL-1+7);

BINSIZE_HZ          = 24414;
KHZ_TO_HZ           = 1e3;
MHZ_TO_KHZ          = 1e3;
MHZ_TO_HZ           = 1e6;

SECONDS_PER_DAY     = 86400; DAYS_PER_WEEK = 7;
SECONDS_PER_WEEK    = SECONDS_PER_DAY*DAYS_PER_WEEK;
MINS_PER_HOUR       = 60;
HOURS_PER_MIN       = 60;
